### ISSUE TITLE
remove My Opera feed from planet

### ISSUE THREAD

**Issue by hallvors** [miketaylr/planet.webcompat.com#13]
No point in having this anymore: 

    [http://my.opera.com/sitepatching/xml/rss/blog/]
    name: Opera Sitepatching updates

Maybe replace it with a dev.opera feed, if there's a suitable one?

**Comment by miketaylr** [comment]
Fixed in https://github.com/webcompat/planet.webcompat.com/commit/28828d4875b0f48c7cecf329c857b24ebdd8e589.

**Comment by miketaylr** [comment]
(only 13 months later...)
